# Generated by Django 5.1.3 on 2024-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Number of patients that can fit in the room (for patient rooms only).', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('OPERATING', 'Operating room'), ('CONSULTATION', 'Consultation room'), ('PATIENT', 'Patient room'), ('TREATMENT', 'Treatment room')], max_length=20),
        ),
    ]
