# Generated by Django 5.1.3 on 2024-11-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_room_capacity_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.room'),
        ),
    ]
